site_name: "The Moonstream Docs"

theme:
  name: material
  logo: assets/moonstream-logo.png
  favicon: images/favicon.png
  font:
    text: Space Grotesk
    code: Space Mono
  palette:
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark-mode
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: spacy
            separate_signature: true
            show_signature_annotations: true
          paths:
            - moonworm
  - search
  - social
  - tags

extra:
  homepage: https://moonstream.to
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/bugout-dev/moonstream"
    - icon: fontawesome/brands/discord
      link: https://discord.gg/pYE65FuNSz
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/moonstreamto"

  generator: false

repo_url: https://github.com/bugout-dev/moonstream-docs

edit_uri: edit/main/docs

copyright: Copyright &copy; 2022 Moonstream.to

watch:
  - moonworm
